@startuml


node "Healthcare Provider" {
  [Responsible Physician] as Doc
}

node "Public Health" {
  [FOPH Reporting System] as FOPH
}

' --- Relations ---
' Direct transmission from the clinician to the FOPH
Doc -right-> FOPH : Transmits Clinical Report 


@enduml