#!/usr/bin/env bash
#
# SDC template-based $extract for the Gonorrhoea testcase.
#
# Pipeline:  sushi .  ->  this script
#
# Runs the CSIRO/aehrc reference $extract (@aehrc/sdc-template-extract) on a Gonorrhoea
# QuestionnaireResponse using the FSH-authored Bundle template (ChEkmDocumentGonorrhoeaTemplate),
# producing a document Bundle conforming to Profile: ChEkmDocumentGonorrhoea.
#
# The questionnaire already carries the extraction template (contained Bundle template +
# sdc-questionnaire-templateExtract, authored in ChEkmQuestionnaireGonorrhoea.fsh) — the same
# wiring Smart Forms needs to offer $extract. The CLI therefore uses it as-is.
#
# Inputs (generated by `sushi .`; assembled questionnaire by tests/assemble-gonorrhoea.sh):
#   - Questionnaire:           the assembled ChEkmQuestionnaireGonorrhoeaAssembled if present
#                              (what the renderer loads), else the modular root
#   - QuestionnaireResponse:   ChEkmQuestionnaireResponseGonorrhoea
#
# Usage:
#   ./tests/extract-gonorrhoea.sh [QUESTIONNAIRE_JSON] [QR_JSON] [OUT_JSON]

set -euo pipefail
cd "$(dirname "$0")/.."

ASSEMBLED="input/resources/Questionnaire-ChEkmQuestionnaireGonorrhoeaAssembled.json"
ROOT="fsh-generated/resources/Questionnaire-ChEkmQuestionnaireGonorrhoea.json"
DEFAULT_Q="$ROOT"
[ -f "$ASSEMBLED" ] && DEFAULT_Q="$ASSEMBLED"

Q="${1:-$DEFAULT_Q}"
QR="${2:-fsh-generated/resources/QuestionnaireResponse-ChEkmQuestionnaireResponseGonorrhoea.json}"
OUT="${3:-fsh-generated/Bundle-ChEkmDocumentGonorrhoea-extracted.json}"

for f in "$Q" "$QR"; do
  [ -f "$f" ] || { echo "ERROR: $f not found. Run 'sushi .' first."; exit 1; }
done

# Install the reference library on first run.
if [ ! -d tests/extract/node_modules ]; then
  echo "Installing @aehrc/sdc-template-extract ..."
  (cd tests/extract && npm install --silent)
fi

echo "Questionnaire:         $Q"
echo "QuestionnaireResponse: $QR"
echo

node tests/extract/extract.cjs "$Q" "$QR" "$OUT"

echo
echo "Extracted document Bundle: $OUT"
command -v jq >/dev/null 2>&1 && jq -r '
  "  type: \(.type)",
  "  entries:",
  (.entry[] | "    - \(.resource.resourceType) \(.fullUrl)")
' "$OUT" || true
