#!/usr/bin/env bash
#
# SDC template-based $extract for the Mpox testcase.
#
# Pipeline:  sushi .  ->  ./scripts/assemble-mpox.sh  ->  this script
#
# Runs the CSIRO/aehrc reference $extract (@aehrc/sdc-template-extract) on a Mpox
# QuestionnaireResponse using the FSH-authored Bundle template (ChEkmDocumentMpoxTemplate),
# producing a document Bundle conforming to Profile: ChEkmDocumentMpox.
#
# Mpox-specific coverage vs. the Gonorrhoea testcase (scripts/extract-gonorrhoea.sh):
#   * `manifestation` repeats (check-box) -> the template's context on evidence[0] must produce
#     ONE Condition.evidence entry PER answered manifestation, each with a single code.
#   * manifestationBeginUnknown=false -> the asserted onsetDateTime branch (Gonorrhoea covers the
#     data-absent branch).
#   * the person group carries full names (surname/givenname), not initials.
#
# Inputs (generated by `sushi .`; assembled questionnaire by scripts/assemble-mpox.sh):
#   - Questionnaire:           the assembled ChEkmQuestionnaireMpoxAssembled if present
#                              (what the renderer loads), else the modular root
#   - QuestionnaireResponse:   ChEkmQuestionnaireResponseMpox
#
# Usage:
#   ./scripts/extract-mpox.sh [QUESTIONNAIRE_JSON] [QR_JSON] [OUT_JSON]

set -euo pipefail
cd "$(dirname "$0")/.."

ASSEMBLED="input/resources/Questionnaire-ChEkmQuestionnaireMpoxAssembled.json"
ROOT="fsh-generated/resources/Questionnaire-ChEkmQuestionnaireMpox.json"
DEFAULT_Q="$ROOT"
[ -f "$ASSEMBLED" ] && DEFAULT_Q="$ASSEMBLED"

Q="${1:-$DEFAULT_Q}"
QR="${2:-fsh-generated/resources/QuestionnaireResponse-ChEkmQuestionnaireResponseMpox.json}"
OUT="${3:-input/resources/Bundle-ChEkmDocumentMpox-extracted.json}"

for f in "$Q" "$QR"; do
  [ -f "$f" ] || { echo "ERROR: $f not found. Run 'sushi .' first."; exit 1; }
done

# Install the reference library on first run.
if [ ! -d scripts/extract/node_modules ]; then
  echo "Installing @aehrc/sdc-template-extract ..."
  (cd scripts/extract && npm install --silent)
fi

echo "Questionnaire:         $Q"
echo "QuestionnaireResponse: $QR"
echo

node scripts/extract/extract.cjs "$Q" "$QR" "$OUT"

# The extract engine emits the document Bundle without an `id`. Since $OUT is a predefined IG
# resource (input/resources/), the IG Publisher needs a stable logical id — add one derived from
# the output filename (Bundle-<id>.json -> <id>, e.g. ChEkmDocumentMpox-extracted), placed
# right after resourceType.
if command -v jq >/dev/null 2>&1; then
  BUNDLE_ID="$(basename "$OUT" .json)"; BUNDLE_ID="${BUNDLE_ID#Bundle-}"
  tmp="$(mktemp)"
  jq --arg id "$BUNDLE_ID" '{resourceType, id: $id} + del(.id)' "$OUT" > "$tmp" && mv "$tmp" "$OUT"
fi

echo
echo "Extracted document Bundle: $OUT"
command -v jq >/dev/null 2>&1 && jq -r '
  "  type: \(.type)",
  "  entries:",
  (.entry[] | "    - \(.resource.resourceType) \(.fullUrl)")
' "$OUT" || true

# Mpox regression check: one evidence entry per answered manifestation, one code each.
if command -v jq >/dev/null 2>&1; then
  echo
  echo "Condition.evidence (expect one entry per answered manifestation):"
  jq -r '
    [.entry[].resource | select(.resourceType == "Condition")][0].evidence
    | to_entries[]
    | "    evidence[\(.key)].code[0].coding[0] = \(.value.code[0].coding[0].code) (\(.value.code[0].coding[0].display))"
  ' "$OUT" || true
fi
