#!/usr/bin/env bash
#
# SDC template-based $extract for the Hepatitis C testcase.
#
# Pipeline:  sushi .  ->  ./scripts/assemble-hepatitisc.sh  ->  this script
#
# Runs the CSIRO/aehrc reference $extract (@aehrc/sdc-template-extract) on a Hepatitis C
# QuestionnaireResponse using the FSH-authored Bundle template (ChEkmDocumentHepatitisCTemplate),
# producing a document Bundle conforming to Profile: ChEkmDocumentHepatitisC.
#
# Hepatitis C-specific coverage vs. the Gonorrhoea and Mpox testcases:
#   * Hospitalisation answered "unbekannt" -> the Encounter entry IS emitted but carries nothing
#     except hospitalization.extension[data-absent-reason] (Mpox covers "ja", Gonorrhoea has no
#     Verlauf at all).
#   * `deceased` = false -> both the cause-of-death Observation entry and section[cause-death] are
#     dropped, i.e. the CLOSED state of the second conditional entry.
#   * Exposure "Wo" with the country answered as "unbekannt" and a precise location given ->
#     Address._country carries a data-absent-reason while `city` is a string (Mpox covers the
#     opposite combination).
#   * The Exposure is the BASE ChEkmExposure: no "Wie" components (see OPEN QUESTIONS #2 in
#     ChEkmQuestionnaireHepatitisC.fsh).
#   * Labor: ONLY the mandatory name and the email are answered, so the eight optional,
#     context-gated elements of the shared ExtractedLabOrganization must all be ABSENT (the invasive
#     pneumococcal disease round trip answers all of them and covers the open state).
#
# Inputs (generated by `sushi .`; assembled questionnaire by scripts/assemble-hepatitisc.sh):
#   - Questionnaire:           the assembled ChEkmQuestionnaireHepatitisCAssembled if present
#                              (what the renderer loads), else the modular root
#   - QuestionnaireResponse:   ChEkmQuestionnaireResponseHepatitisC
#
# Usage:
#   ./scripts/extract-hepatitisc.sh [QUESTIONNAIRE_JSON] [QR_JSON] [OUT_JSON]

set -euo pipefail
cd "$(dirname "$0")/.."

ASSEMBLED="input/resources/Questionnaire-ChEkmQuestionnaireHepatitisCAssembled.json"
ROOT="fsh-generated/resources/Questionnaire-ChEkmQuestionnaireHepatitisC.json"
DEFAULT_Q="$ROOT"
[ -f "$ASSEMBLED" ] && DEFAULT_Q="$ASSEMBLED"

Q="${1:-$DEFAULT_Q}"
QR="${2:-fsh-generated/resources/QuestionnaireResponse-ChEkmQuestionnaireResponseHepatitisC.json}"
OUT="${3:-input/resources/Bundle-ChEkmDocumentHepatitisC-extracted.json}"

for f in "$Q" "$QR"; do
  [ -f "$f" ] || { echo "ERROR: $f not found. Run 'sushi .' first."; exit 1; }
done

# Install the reference library on first run.
if [ ! -d scripts/extract/node_modules ]; then
  echo "Installing @aehrc/sdc-template-extract ..."
  (cd scripts/extract && npm install --silent)
fi

echo "Questionnaire:         $Q"
echo "QuestionnaireResponse: $QR"
echo

node scripts/extract/extract.cjs "$Q" "$QR" "$OUT"

# The extract engine emits the document Bundle without an `id`. Since $OUT is a predefined IG
# resource (input/resources/), the IG Publisher needs a stable logical id — add one derived from
# the output filename (Bundle-<id>.json -> <id>), placed right after resourceType.
if command -v jq >/dev/null 2>&1; then
  BUNDLE_ID="$(basename "$OUT" .json)"; BUNDLE_ID="${BUNDLE_ID#Bundle-}"
  tmp="$(mktemp)"
  jq --arg id "$BUNDLE_ID" '{resourceType, id: $id} + del(.id)' "$OUT" > "$tmp" && mv "$tmp" "$OUT"
fi

echo
echo "Extracted document Bundle: $OUT"
command -v jq >/dev/null 2>&1 && jq -r '
  "  type: \(.type)",
  "  entries:",
  (.entry[] | "    - \(.resource.resourceType) \(.fullUrl)")
' "$OUT" || true

# Hepatitis C regression checks.
if command -v jq >/dev/null 2>&1; then
  echo
  echo "Condition.evidence (expect one entry per answered manifestation):"
  # `evidence` is absent when `manifestation` was not answered — e.g. when the input QR came
  # straight from $populate, which has no initialExpression for it. Guard with `// []` so that is
  # reported as "none" instead of a jq null error.
  jq -r '
    ([.entry[].resource | select(.resourceType == "Condition")][0].evidence // [])
    | if length == 0 then "    (none — manifestation unanswered)"
      else to_entries[]
        | "    evidence[\(.key)].code[0].coding[0] = \(.value.code[0].coding[0].code) (\(.value.code[0].coding[0].display))"
      end
  ' "$OUT" || true
  echo
  echo "Manifestationsbeginn unbekannt (expect _onsetDateTime with a data-absent-reason, no value):"
  jq -r '[.entry[].resource | select(.resourceType == "Condition")][0]
         | "    onsetDateTime = \(.onsetDateTime // "(absent)")  _onsetDateTime = \(._onsetDateTime.extension[0].valueCode // "(none)")"' "$OUT" || true
  echo
  echo "Hospitalisation unbekannt (expect an Encounter whose only content is the data-absent-reason):"
  jq -r '([.entry[].resource | select(.resourceType == "Encounter")][0]
         | "    hospitalization = \(.hospitalization // "(absent)")") // "    (no Encounter emitted)"' "$OUT" || true
  echo
  echo "Alive (expect NO cause-of-death Observation and no section[cause-death]):"
  jq -r '"    cause-of-death Observations: \([.entry[].resource | select(.resourceType == "Observation" and .code.coding[0].code == "79378-6")] | length)",
         "    Composition sections:        \([.entry[].resource | select(.resourceType == "Composition")][0].section | map(.code.coding[0].code) | join(", "))"' "$OUT" || true
  echo
  echo "Labor (ONLY name + email answered — expect NO department/address/phone/identifier):"
  jq -r '([.entry[].resource | select(.resourceType == "Organization" and .id == "ExtractedLabOrganization")][0]
         | "    name       = \(.name // "(absent)")",
           "    department = \(.extension[0].valueString // "(none)")",
           "    address    = \(if .address then (.address[0] | "\(.line[0] // "-") / \(.postalCode // "-") \(.city // "-")") else "(none)" end)",
           "    telecom    = \(if .telecom then (.telecom | map("\(.system)=\(.value)") | join(", ")) else "(none)" end)",
           "    identifier = \(if .identifier then (.identifier | map(.value) | join(", ")) else "(none)" end)") // "    (no lab Organization emitted)"' "$OUT" || true
  echo
  echo "section[laboratory] (expect one entry -> the ServiceRequest that carries the lab):"
  jq -r '([.entry[].resource | select(.resourceType == "Composition")][0].section[]
         | select(.code.coding[0].code == "30954-2")
         | "    entries: \(.entry | map(.reference) | join(", "))") // "    (no laboratory section)"' "$OUT" || true
  echo
  echo "Exposure Wo (expect _country with a data-absent-reason and city = Bern):"
  jq -r '[.entry[].resource | select(.resourceType == "Observation")][]
         | select(.code.coding[0].code == "EXPAGNT")
         | .extension[0].valueAddress
         | "    country = \(.country // "(absent)")  _country = \(._country.extension[0].valueCode // "(none)")  city = \(.city // "(absent)")"' "$OUT" || true
fi
