#!/usr/bin/env bash
#
# SDC template-based $extract for the invasive pneumococcal disease testcase.
#
# Pipeline:  sushi .  ->  ./scripts/assemble-invasivepneumococcaldisease.sh  ->  this script
#
# Runs the CSIRO/aehrc reference $extract (@aehrc/sdc-template-extract) on an invasive pneumococcal
# disease QuestionnaireResponse using the FSH-authored Bundle template
# (ChEkmDocumentInvasivePneumococcalDiseaseTemplate), producing a document Bundle conforming to
# Profile: ChEkmDocumentInvasivePneumococcalDisease.
#
# Coverage vs. the Gonorrhoea, Mpox and Hepatitis C testcases:
#   * The INITIALS person module together with a "Verlauf" section (Gonorrhoea is the other initials
#     form and has no Verlauf).
#   * `manifestation` answered exactly ONCE -> exactly one Condition.evidence entry (Mpox: three,
#     Hepatitis C: two).
#   * Hospitalisation answered "nein" -> NO Encounter entry at all, and neither Composition.encounter
#     nor Condition.encounter. Mpox covers "ja", Hepatitis C "unbekannt" — this is the third state.
#   * Died WITHOUT a date of death -> Patient.deceasedDateTime valueless with
#     data-absent-reason#asked-unknown (Mpox: died + date, Hepatitis C: alive).
#   * Todesursache "unbekannt" -> the SNOMED qualifier passed through into valueCodeableConcept and
#     NO Observation.focus (Mpox answers "reported pathogen" and covers the focus branch).
#   * Exposure "Wo" with the country answered and the precise location "unbekannt" -> Address.country
#     plus `_city` with a data-absent-reason (Mpox: both given, Hepatitis C: the opposite).
#   * The Exposure is the BASE ChEkmExposure: no "Wie" components (see OPEN QUESTIONS #5 in
#     ChEkmQuestionnaireInvasivePneumococcalDisease.fsh).
#   * Impfstatus (issue #29): "ja" with a TOTAL of 2 doses, NO last-dose date and the product TYPED
#     rather than picked -> the UndatedDosed Immunization variant (occurrenceDateTime valueless with
#     a data-absent-reason) and the `ofType(string)` leg of the vaccineCode expression
#     (vaccineCode.text = the typed name, coding[0] left as the SNOMED CT fallback product). Mpox
#     covers DatedDosed with a picked brand Coding, and the "unknown" Observation.
#
# Inputs (generated by `sushi .`; assembled questionnaire by scripts/assemble-invasivepneumococcaldisease.sh):
#   - Questionnaire:           the assembled ChEkmQuestionnaireInvasivePneumococcalDiseaseAssembled
#                              if present (what the renderer loads), else the modular root
#   - QuestionnaireResponse:   ChEkmQuestionnaireResponseInvasivePneumococcalDisease
#
# Usage:
#   ./scripts/extract-invasivepneumococcaldisease.sh [QUESTIONNAIRE_JSON] [QR_JSON] [OUT_JSON]

set -euo pipefail
cd "$(dirname "$0")/.."

ASSEMBLED="input/resources/Questionnaire-ChEkmQuestionnaireInvasivePneumococcalDiseaseAssembled.json"
ROOT="fsh-generated/resources/Questionnaire-ChEkmQuestionnaireInvasivePneumococcalDisease.json"
DEFAULT_Q="$ROOT"
[ -f "$ASSEMBLED" ] && DEFAULT_Q="$ASSEMBLED"

Q="${1:-$DEFAULT_Q}"
QR="${2:-fsh-generated/resources/QuestionnaireResponse-ChEkmQuestionnaireResponseInvasivePneumococcalDisease.json}"
OUT="${3:-input/resources/Bundle-ChEkmDocumentInvasivePneumococcalDisease-extracted.json}"

for f in "$Q" "$QR"; do
  [ -f "$f" ] || { echo "ERROR: $f not found. Run 'sushi .' first."; exit 1; }
done

# Install the reference library on first run.
if [ ! -d scripts/extract/node_modules ]; then
  echo "Installing @aehrc/sdc-template-extract ..."
  (cd scripts/extract && npm install --silent)
fi

echo "Questionnaire:         $Q"
echo "QuestionnaireResponse: $QR"
echo

node scripts/extract/extract.cjs "$Q" "$QR" "$OUT"

# The extract engine emits the document Bundle without an `id`. Since $OUT is a predefined IG
# resource (input/resources/), the IG Publisher needs a stable logical id — add one derived from
# the output filename (Bundle-<id>.json -> <id>), placed right after resourceType.
if command -v jq >/dev/null 2>&1; then
  BUNDLE_ID="$(basename "$OUT" .json)"; BUNDLE_ID="${BUNDLE_ID#Bundle-}"
  tmp="$(mktemp)"
  jq --arg id "$BUNDLE_ID" '{resourceType, id: $id} + del(.id)' "$OUT" > "$tmp" && mv "$tmp" "$OUT"
fi

echo
echo "Extracted document Bundle: $OUT"
command -v jq >/dev/null 2>&1 && jq -r '
  "  type: \(.type)",
  "  entries:",
  (.entry[] | "    - \(.resource.resourceType) \(.fullUrl)")
' "$OUT" || true

# Invasive pneumococcal disease regression checks.
if command -v jq >/dev/null 2>&1; then
  echo
  echo "Condition.evidence (expect EXACTLY ONE entry — Sepsis):"
  jq -r '
    ([.entry[].resource | select(.resourceType == "Condition")][0].evidence // [])
    | if length == 0 then "    (none — manifestation unanswered)"
      else to_entries[]
        | "    evidence[\(.key)].code[0].coding[0] = \(.value.code[0].coding[0].code) (\(.value.code[0].coding[0].display))"
      end
  ' "$OUT" || true
  echo
  echo "Manifestationsbeginn known (expect onsetDateTime = 2026-01-27, no data-absent-reason):"
  jq -r '[.entry[].resource | select(.resourceType == "Condition")][0]
         | "    onsetDateTime = \(.onsetDateTime // "(absent)")  _onsetDateTime = \(._onsetDateTime.extension[0].valueCode // "(none)")"' "$OUT" || true
  echo
  echo "Hospitalisation nein (expect NO Encounter, and no Composition.encounter / Condition.encounter):"
  jq -r '"    Encounters:            \([.entry[].resource | select(.resourceType == "Encounter")] | length)",
         "    Composition.encounter: \([.entry[].resource | select(.resourceType == "Composition")][0].encounter // "(absent)" | tostring)",
         "    Condition.encounter:   \([.entry[].resource | select(.resourceType == "Condition")][0].encounter // "(absent)" | tostring)"' "$OUT" || true
  echo
  echo "Died, date unknown (expect deceasedDateTime absent with _deceasedDateTime data-absent-reason):"
  jq -r '[.entry[].resource | select(.resourceType == "Patient")][0]
         | "    deceasedDateTime = \(.deceasedDateTime // "(absent)")  _deceasedDateTime = \(._deceasedDateTime.extension[0].valueCode // "(none)")"' "$OUT" || true
  echo
  echo "Todesursache unbekannt (expect value = sct#261665006 and NO focus):"
  jq -r '([.entry[].resource | select(.resourceType == "Observation" and .code.coding[0].code == "79378-6")][0]
         | "    value = \(.valueCodeableConcept.coding[0].code) (\(.valueCodeableConcept.coding[0].display))  focus = \(.focus // "(absent)" | tostring)") // "    (no cause-of-death Observation emitted)"' "$OUT" || true
  echo
  echo "Impfstatus (expect ONE Immunization: total 2 doses, occurrence DAR, typed brand in .text):"
  jq -r '([.entry[].resource | select(.resourceType == "Immunization")]
         | if length == 0 then ["    (no Immunization emitted)"]
           else map("    doseNumberPositiveInt = \(.protocolApplied[0].doseNumberPositiveInt // "(absent)")  _doseNumber = \(.protocolApplied[0]._doseNumberPositiveInt.extension[0].valueCode // "(none)")",
                    "    targetDisease         = \(.protocolApplied[0].targetDisease[0].coding[0].code)",
                    "    occurrenceDateTime    = \(.occurrenceDateTime // "(absent)")  _occurrenceDateTime = \(._occurrenceDateTime.extension[0].valueCode // "(none)")",
                    "    vaccineCode           = \(.vaccineCode.coding[0].code // "(none)")  text = \(.vaccineCode.text // "(none)")")
           end) + ["    Immunizations: \([.entry[].resource | select(.resourceType == "Immunization")] | length)  vaccination-status Observations: \([.entry[].resource | select(.resourceType == "Observation" and .code.coding[0].code == "408864009")] | length)"]
         | .[]' "$OUT" || true
  echo
  echo "section[immunization] (expect exactly one entry, pointing at the Immunization above):"
  jq -r '([.entry[].resource | select(.resourceType == "Composition")][0].section[]
         | select(.code.coding[0].code == "11369-6")
         | "    entries: \(.entry | map(.reference) | join(", "))") // "    (no immunization section)"' "$OUT" || true
  echo
  echo "Exposure Wo (expect country = CH and _city with a data-absent-reason, no city string):"
  jq -r '[.entry[].resource | select(.resourceType == "Observation")][]
         | select(.code.coding[0].code == "EXPAGNT")
         | .extension[0].valueAddress
         | "    country = \(.country // "(absent)")  city = \(.city // "(absent)")  _city = \(._city.extension[0].valueCode // "(none)")"' "$OUT" || true
fi
